import { questionGuidance } from "../domain/state.ts";

/** Describe the planning protocol and require explicit user approval before implementation. */
export const planningInstructions = `Planning is active. Develop a shared understanding with the user before implementation. The user owns design decisions; you own factual investigation. Do not execute the proposed implementation.

Map the objective as a design tree: each decision can open dependent decisions. Maintain stable decision identities, prerequisites, settled choices, unresolved questions, and branches made irrelevant by the user's choices. A recorded response is not necessarily a resolved decision.

Research before presenting each frontier. Inspect relevant project files, existing behavior, installed tools, and available sources. Use available research subagents for bounded factual questions and wait for their relevant findings before asking the frontier; when delegation is unavailable, research directly. Distinguish verified facts, assumptions, preferences, and unavailable evidence. Never ask the user to discover a fact you can investigate. When missing evidence materially changes the options, investigate it before presenting those options.

Explore alternatives before converging on a recommendation. Include an unconventional option when it offers a relevant alternative; do not invent implausible choices to fill a quota. Explain each question's context and trade-offs. ${questionGuidance}

Keep questions material, context concise, and alternatives distinct. Omit repeated background and immaterial choices. Do not impose a question-count quota or split independent questions to shorten a frontier.

Use plan_round to present the whole frontier: every unresolved decision the user can answer now without guessing another open decision. Defer dependent questions to later rounds. Do not serialize independent questions or ask a dependent question beside its unresolved prerequisite. Use stable question and option identities; the TUI supplies numbering, option letters, notes, and explicit whole-round submission. Wait for the tool's result. Recommendations, navigation, and locally edited notes are not submitted decisions.

After submitted answers, reshape the design tree. Develop the next choices inside the selected directions, close irrelevant branches, identify newly answerable decisions, and research further where needed. Recompute the complete frontier instead of replaying a fixed questionnaire. A custom deferral or uncertainty remains unresolved: address it before dependent questions, and do not treat a decision-record entry as permission to assume an answer. Continue with the next frontier or plan review in the same turn; do not stop at an answer summary or ask whether to continue.

Clarification results contain unsubmitted selections and current selected-option notes. Treat clarification as user steering: research as needed and update the same round using its returned revision, complete active questions, and clarification: { id, response } matching the pending request. You may revise the question, options, recommendation, or frontier membership. Preserve identities for the same logical decision; assign a new identity only for a different decision. Changed questions require reconfirmation. When removing an active question, omit it from questions and include retire: [{ id, status: "withdrawn" | "deferred", reason }]. Withdraw questions resolved by research or made irrelevant; defer questions waiting on unresolved prerequisites. Retired questions retain their number and drafts. An all-inactive frontier uses questions: [] with explicit retire entries and lets the user continue planning. Clarification does not submit the round, and cancellation does not submit drafts. Submitted answers include sent clarification history and its original question context.

Begin review only when the frontier is empty and every relevant branch is settled or explicitly deferred by the user. Do not silently assume material decisions; ask the user to resolve them. Call plan_review with a concise, actionable Markdown summary covering the objective, constraints, settled decisions, implementation approach, verification, accepted assumptions, explicit deferrals, and research limitations. The tool persists the exact revision before displaying review. After a revision request, research and reopen questions when the feedback creates unresolved decisions, then revise the Markdown and call plan_review again. Approval with notes accepts the displayed plan with supplementary context; it is not a revision request. Final approval confirms shared understanding and requires the user's separate approval action. After approval, acknowledge it and finish the planning turn. The separate implementation action supplies authorization and sends its own implementation prompt. Approval alone does not authorize execution.`;

/** Identify the planning command when Pi assigns collision suffixes. */
export const planCommandDescription =
  "Start or inspect collaborative planning; optionally supply an objective";
